### ISSUE TITLE
Not pulling content 

### ISSUE THREAD

**Issue by Biblefast** [IronMooseDevelopment/FoundryVTT-dScryb-public#1]
I installed the module and enabled it on the module setting directory. It does not pull any content into Journal Entries.

Thanks

**Comment by cswendrowski** [comment]
Howdy @Biblefast - we've recently deployed an API update to resolve some issues with Syncing.
Can you verify it's still occurring, and if so, let me know:
1) What System + Version you're on
2) If you have any errors in the Console (F12)?

**Comment by cswendrowski** [comment]
Closing in favor of #3
