### ISSUE TITLE
Subscribed user not getting full content on Sync

### ISSUE THREAD

**Issue by leagueoffoundryvttdevs** [IronMooseDevelopment/FoundryVTT-dScryb-public#3]
**Submitted By**: dscryb@intuitivelyobvious.net
**Feedback Type**: Bug
 
**Core:** 0.7.9
**System:** dnd5e v1.2.4
**Module Version:** dscryb v1.0.0
 
**Description**:
Here is the report you requested.

**Comment by cswendrowski** [comment]
Howdy - we've recently deployed an API update to resolve some issues with Syncing.
Can you verify it's still occurring, and if so, let me know if you have any errors in the Console (F12)?

**Comment by Biblefast** [comment]
Will do this afternoon when I get off work

Brent Eudy

**Comment by kunxin-chor** [comment]
Can confirm that this issue still exists. I paid for a membership and is unable to sync to get the full set of descriptions.

**Comment by Biblefast** [comment]
Still not syncing 

Brent Eudy

**Comment by insquared** [comment]
can confirm, having the same issue, my dscryb is on the latest update.

**Comment by cswendrowski** [comment]
Version 1.0.1 has been released, with increased security checks and messaging around the login and sync paths. Please update and let me know!

**Comment by cswendrowski** [comment]
Closing until I hear further issue
