### ISSUE TITLE
Subscribed but the content is not importing

### ISSUE THREAD

**Issue by leagueoffoundryvttdevs** [IronMooseDevelopment/FoundryVTT-dScryb-public#4]
**Submitted By**: Josh
**Feedback Type**: Bug
 
**Core:** 0.7.9
**System:** dnd5e v1.2.4
**Module Version:** dscryb v1.0.0
 
**Description**:
I attempted to sync all of my dscryb content, but it keeps telling me I need a subscription for all of them, but I already am subscribed.

Proof: https://imgur.com/a/Q5mAO0T<details>
<summary>Module Settings</summary>

```js

```
</details>
<details>
<summary>Active Modules</summary>
ATL--v0.2.09;
ActiveAuras--v0.2.07;
CautiousGamemastersPack--v0.1.6;
CommunityLighting--v0.3.1;
Custom-Token-Animations--v0.1.10;
Dynamic-Effects-SRD--v4.1.11;
JB2A_DnD5e--v0.1.6;
SocketSettings--v0.0.3;
TinyTokens--v0.0.4;
TokenHotbar--v4.2.1;
WallCutter--v1.1.0;
_chatcommands--v1.3.2;
alternative-rotation--v1.1.0;
autocomplete-inline-properties--v1.2.0;
automated-jb2a-animations--v0.2.75;
baileywiki-maps--v0.2.7;
better-rolltables--v1.6.4;
bug-reporter--v1.2.1;
character-actions-list-5e--v3.0.3;
chat-images--v2.5.0;
colorsettings--v2.5.7;
compendium-browser--v0.4.5;
condition-automation--v2.2.6;
cursor-hider--v1.1.7;
dae--v0.2.59;
ddb-game-log--v0.10.2;
ddb-importer--v0.6.25;
ddd-beginner-baubles--v1.0.1;
df-architect--v1.0.0;
df-curvy-walls--v2.1.1;
df-qol--v1.0.0;
df-settings-clarity--v3.1.0;
drag-ruler--v1.4.5;
dragonfiremaps--v1.1.13;
dragonfiremapspremium--v1.1.9;
dscryb--v1.0.0;
dynamic-illumination--v0.9.0;
easy-target--v2.10;
foundry_community_macros--v0.37;
furnace--v2.6.0;
fxmaster--v1.0.3;
hey-wait--v0.3.0;
hide-gm-rolls--v0.6.3;
inlinewebviewer--v2.2.4;
jb2a_patreon--v0.1.6.2;
lib-df-hotkeys--v2.3.3;
lib-wrapper--v1.3.6.0;
loot-tavern-compendium--v1.7.0;
lootsheetnpc5e--v3.0.2;
michaelghelfi--v1.2;
midi-qol--v0.3.98;
minimal-ui--v0.5.3;
monks-hotbar-expansion--v1.0.6;
multilevel-tokens--v1.3.4;
notokenanim--v3.0;
parallaxia--v0.2.13;
pdfoundry--v0.8.5;
permission_viewer--v0.8.5;
pick-up-stix--v0.13.8;
pin-fixer--v1.0.4;
pointer--v2.3.1;
popout--v1.0;
quick-insert--v2.4.4;
rolladvantage-token-stamp-2-foundry--v1.1.1;
roofs--v0.2.1;
scene-defaults--v1.0.2;
select-tool-everywhere--v1.1.1;
shared-token-visibility--v0.2.2;
sheet-macro--v1.3;
stairways--v0.4.0;
tabletop-rpg-music--v1.2.1;
tidy-ui_game-settings--v0.1.21;
tidy5e-sheet--v0.4.25;
token-attacher--v4.0.2;
token-hud-wildcard--v1.2.0;
tokenmagic--v0.4.4;
trigger-happy--v0.8.1;
vtta-iconizer--v2.1.15;
wall-height--v3.5.3.4;
zsync--v0.0.4;
forge-vtt--vundefined;
</details>

**Comment by cswendrowski** [comment]
Closing in favor of #3
