### ISSUE TITLE
Can't sync at all.

### ISSUE THREAD

**Issue by leagueoffoundryvttdevs** [IronMooseDevelopment/FoundryVTT-dScryb-public#7]
**Submitted By**: nickallenking@gmail.com
**Feedback Type**: Bug
 
**Core:** 0.7.9
**System:** dnd5e v1.2.4
**Module Version:** dscryb v1.0.2
 
**Description**:
I synced my account and received the free content. I then upgraded to Hero and went to sync again. My console shows an error and the module does nothing else. It also didn't import the macros at all before I upgraded.<details>
<summary>Module Settings</summary>

```js

```
</details>
<details>
<summary>Active Modules</summary>
ambientdoors--v2.2.3;
animated-spell-effects--v0.6.5;
autocomplete-whisper--v0.3.3;
bellows--v0.3.2;
better-rolltables--v1.6.4;
BetterAmbientLoop--v1.1.2.1;
BonusDie--v1.0.0;
camera-follow-token--v0.3.1;
chat-images--v2.5.0;
chat-notifications--v1.2.2;
combat-utility-belt--v1.4.0;
cursor-hider--v1.1.7;
dd-import--v1.1.1;
dice-calculator--v0.6.6;
difficultterrain--v1.0.10;
easy-target--v2.10;
encounter-builder--v0.2.2;
fa-dm-screen--v0.4.1;
forien-custom-fonts--v0.1.3;
forien-unidentified-items--v0.2.5;
furnace--v2.6.0;
fxmaster--v1.0.3;
gm-notes--v0.3;
healthEstimate--v2.4.0;
jaamod--v0.2;
journal-link--v1.0.0;
legendkeeper-integration--v1.1.0;
lets-trade-5e--v0.2.0;
maestro--v0.7.4;
magicitems--v2.0.8;
mergewalls--v0.0.13;
minimize-button--v0.1.0;
pdfoundry--v0.8.5;
pings--v1.2.10;
playlist-ui--v1.0.0;
quick-encounters--v0.7.3;
resetdoorsandfog--v1.0.1;
roofs--v0.2.1;
select-tool-everywhere--v1.1.1;
ShowDragDistance--v2.2.3;
summoner--v0.1.4;
token-chat-link--v1.1.0;
torch--v1.1.4;
travel-pace--v1.0.1;
turnAlert--v1.5.1;
turnmarker--v2.6.9;
tweakplaylist--v0.4.5.11;
vehicles-and-mechanisms--v0.3.0;
vtta-iconizer--v2.1.15;
workshop-ammo-swapper--v0.1.2;
_sortablejs--v1.10.2-fvtt1;
displaymode--v0.5;
mad-urbanext--v1.5;
_chatcommands--v1.3.2;
ddb-game-log--v0.10.2;
DiscordConnect--v1.0.5;
smip-compendium--v0.5.0;
about-time--v0.1.68;
free-loot-tavern-compendium--v1.9.1;
monks-scene-navigation--v1.0.11;
token-attacher--v4.0.2;
df-chat-enhance--v3.0.2;
compendium-folders--v2.2.41;
Dynamic-Effects-SRD--v4.1.12;
foundry_community_tables--v0.13;
gm-screen--v2.4.0;
lib-wrapper--v1.5.2.0;
multilevel-tokens--v1.4.1;
theatre--v1.16.2;
tidy-ui_game-settings--v0.1.22;
token-action-hud--v1.0.15;
dae--v0.2.62;
forien-quest-log--v0.5.7;
fvtt-keikaku--v0.2.0;
lootsheetnpc5e--v3.0.3;
monks-tokenbar--v1.0.34;
narrator-tools--v0.53;
SoundBoard--v1.4.0;
tidy5e-sheet--v0.4.29;
tokenmagic--v0.5.0;
npcgen--v0.5.0;
Next-Up--v0.0.59;
my-shared-content--v1.0.0;
dice-so-nice--v3.3.3;
mob-attack-tool--v0.1.26;
multiattack-5e--v4.4.2;
find-the-culprit--v1.3.3;
JB2A_DnD5e--v0.1.8;
midi-qol--v0.3.103;
foundryvtt-simple-calendar--vv1.2.35;
socketlib--v1.0.5;
polyglot--v1.5.17.1;
dscryb--v1.0.2;
bug-reporter--v1.2.1;
</details>

**Comment by cswendrowski** [comment]
Hey there Nick - could you share the error you got in Console?
You will need to sign in with your dScryb account via the Login button in the Settings tab to get your new content.

The macros are delivered via updating the Module itself in Foundry's Setup page

**Comment by scooper4711** [comment]
I'm also getting an error now since upgrading to the latest version of the plugin.
ncaught (in promise) TypeError: Cannot read property 'map' of null
    at dscrybApi.loadUserInfo (dscrybApi.mjs:94)
    at async dscrybManager.sync (dscrybManager.mjs:107)
loadUserInfo @ dscrybApi.mjs:94
async function (async)
sync @ dscrybManager.mjs:107
(anonymous) @ dscryb.js:76
dispatch @ jquery.min.js:2
v.handle @ jquery.min.js:2

**Comment by scooper4711** [comment]
Looks like the call for active memberships is returning null. This is line 94:
  this.activeMemberships = user.active_memberships.map(x => x.id.toString());

**Comment by scooper4711** [comment]
console.log(userResponse);
VM83697:1 Response {type: "cors", url: "https://dscryb.azurewebsites.net/api/GetActiveMemb…<redacted>", redirected: false, status: 200, ok: true, …}

**Comment by cswendrowski** [comment]
@scooper4711 the Wordpress instance hosting the dScryb membership info was briefly down, it is now back up. I will make sure to put in a protection for this case in the next version of the module.

You should now be able to retest

**Comment by scooper4711** [comment]
That fixed it.

**Comment by scooper4711** [comment]
So I’m not the original reporter if this issue. Fixing it for me may or may not have fixed it for OP
